### ISSUE TITLE
model to save without needing to leave current route 

### ISSUE THREAD

**Issue by BransonGitomeh** [jamemackson/sane-examples-one-to-many#1]
currently we have to have a full route for saving a new model where the routes model declares a new instance of the model,

i was wondering if we can make the models inside the same template that shows the rest of the models gotten from the server, without having to have a totally new model hook, and route and template and all that?

**Comment by BransonGitomeh** [comment]
but then again we can have the outlet appear whenever we want but what about in situations where we want to have comments for posts for the status's inside how-to-sane...or the comments on the newsfeed inside facebook :-)

**Comment by jamemackson** [comment]
I would think something like this should be possible.  I would have to think about this a bit to come up with a working model for this without using the routes though.  @mgenev, would you have any ideas about this off the top of your head?

**Comment by jamemackson** [comment]
alright, I came up with a simple approach to this.  I'm guessing this could be improved upon a lot, maybe employing a component instead of the way I did it but I haven't yet ventured too far with components (but that's on my todo list).  

Here's the commit with what I came up with super quickly...  https://github.com/jamemackson/sane-examples-one-to-many/commit/dbbb2a59dfd12d32f935183169c7d576543f7962

**Comment by BransonGitomeh** [comment]
awesome, lemme play with that ill give feedback

**Comment by BransonGitomeh** [comment]
working like magic, do we close this now or do we wait for improvements

**Comment by jamemackson** [comment]
glad it worked for you.  I'm guessing we can close it out for now.

if anyone has any improvements, feel free to fork and give a PR and we'll incorporate it into the example.  That or just hit me up on gitter and we can chat about it and/or reopen this issue if desired.

**Comment by BransonGitomeh** [comment]
currently the project is using **$(#element-id).val()** to get values to be used by the childs entered values to use when making a child, can we do **{{input placeholder="name" value=name}}** so we can do **{{name}}** on the entering table so it looks real time, like you did with the parent entering table section
